- id: background
  access_method: http
  sources:
    - id: only
      urls:
        - 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/raster/NE2_LR_LC_SR_W.zip'
  metadata:
    title: 'Natural Earth II with Shaded Relief and Water (10m)'
    abstract: 'Natural Earth II (Public Domain)'
    citation:
      text: 'Made with Natural Earth'
      url: 'https://github.com/nvkelso/natural-earth-vector/blob/master/LICENSE.md'


- id: populated_places
  access_method: http
  sources:
    - id: only
      urls:
        - 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places_simple.zip'
  metadata:
    title: 'Natural Earth Populated Places (10m)'
    abstract: 'Natural Earth Populated Places (Public Domain)'
    citation:
      text: 'Made with Natural Earth'
      url: 'https://github.com/nvkelso/natural-earth-vector/blob/master/LICENSE.md'


- id: coastlines
  access_method: http
  sources:
    - id: only
      urls:
        - 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_coastline.zip'
  metadata:
    title: 'Natural Earth Coastlines (10m)'
    abstract: 'Natural Earth Coastlines (Public Domain)'
    citation:
      text: 'Made with Natural Earth'
      url: 'https://github.com/nvkelso/natural-earth-vector/blob/master/LICENSE.md'


- id: land_shape
  access_method: http
  sources:
    - id: only
      urls:
        - 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_land.zip'
  metadata:
    title: 'Natural Earth Land (10m)'
    abstract: 'Natural Earth Land (Public Domain)'
    citation:
      text: 'Made with Natural Earth'
      url: 'https://github.com/nvkelso/natural-earth-vector/blob/master/LICENSE.md'


# TODO: This data is read as invalid by geopandas. Workaround with
# `gdf.buffer(0)` or replace with a different dataset with valid geometries to
# avoid spending compute time fixing the data. Submit bug report to NE?
# - id: ocean_shape
#   access_method: http
#   sources:
#     - id: only
#       urls:
#         - 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_ocean.zip'
#   metadata:
#     title: 'Natural Earth Ocean (10m)'
#     abstract: 'Natural Earth Ocean (Public Domain)'
#     citation:
#       text: 'Made with Natural Earth'
#       url: 'https://github.com/nvkelso/natural-earth-vector/blob/master/LICENSE.md'


- id: arctic_dem
  access_method: http
  sources:
    - id: only
      urls:
        - 'http://data.pgc.umn.edu/elev/dem/setsm/ArcticDEM/mosaic/v3.0/1km/arcticdem_mosaic_1km_v3.0.tif'
  metadata:
    title: 'Arctic DEM (1km mosaic)'
    abstract: 'ArcticDEM is an NGA-NSF public-private initiative to automatically produce a high-resolution, high quality, digital surface model (DSM) of the Arctic using optical stereo imagery, high-performance computing, and open source photogrammetry software.'
    citation:
      text: 'Data provided by the Polar Geospatial Center. Porter, Claire; Morin, Paul; Howat, Ian; Noh, Myoung-Jon; Bates, Brian; Peterman, Kenneth; Keesey, Scott; Schlenk, Matthew; Gardiner, Judith; Tomko, Karen; Willis, Michael; Kelleher, Cole; Cloutier, Michael; Husby, Eric; Foga, Steven; Nakamura, Hitomi; Platson, Melisa; Wethington, Michael, Jr.; Williamson, Cathleen; Bauer, Gregory; Enos, Jeremy; Arnold, Galen; Kramer, William; Becker, Peter; Doshi, Abhijit; D’Souza, Cristelle; Cummens, Pat; Laurier, Fabien; Bojesen, Mikkel, 2018, “ArcticDEM”, https://doi.org/10.7910/DVN/OHHUKH, Harvard Dataverse, V1, 2020-01-23'
      url: 'https://www.pgc.umn.edu/data/arcticdem/'


- id: bedmachine
  access_method: cmr
  sources:
    - id: only
      granule_ur: 'SC:IDBMG4.003:160281892'
  metadata:
    title: 'IceBridge BedMachine Greenland, Version 3'
    abstract: 'This data set contains a bed topography/bathymetry map of Greenland based on mass conservation, multi-beam data, and other techniques. It also includes surface elevation and ice thickness data, as well as an ice/ocean/land mask.'
    citation:
      text: 'Morlighem, M. et al. 2017, updated 2018. IceBridge BedMachine Greenland, Version 3. [Indicate subset used]. Boulder, Colorado USA. NASA National Snow and Ice Data Center Distributed Active Archive Center. doi: https://doi.org/10.5067/2CIX82HUV88Y. 2020/02/07.'
      url: 'https://doi.org/10.5067/2CIX82HUV88Y'


- id: velocity_mosaic
  access_method: http
  sources:
    - id: only
      urls:
        - 'http://its-live-data.jpl.nasa.gov.s3.amazonaws.com/velocity_mosaic/landsat/v00.0/static/GRE_G0120_0000.nc'
  metadata:
    title: 'Regional Glacier and Ice Sheet Surface Velocities'
    abstract: 'The Inter-mission Time Series of Land Ice Velocity and Elevation (ITS_LIVE) project facilitates ice sheet, ice shelf and glacier research by providing a globally comprehensive and temporally dense multi-sensor record of land ice velocity and elevation with low latency.'
    citation:
      text: 'Velocity data generated using auto-RIFT (Gardner et al., 2018) and provided by the NASA MEaSUREs ITS_LIVE project (Gardner et al., 2019).'
      url: 'https://its-live.jpl.nasa.gov/#documentation'

- id: glacier_terminus
  access_method: cmr
  sources:
    - id: glacier_ids
      granule_ur: 'SC:NSIDC-0642.001:125854253'
    - id: '2000_2001'
      granule_ur: 'SC:NSIDC-0642.001:125860172'
    - id: '2005_2006'
      granule_ur: 'SC:NSIDC-0642.001:125860185'
    - id: '2006_2007'
      granule_ur: 'SC:NSIDC-0642.001:125860176'
    - id: '2007_2008'
      granule_ur: 'SC:NSIDC-0642.001:125860183'
    - id: '2008_2009'
      granule_ur: 'SC:NSIDC-0642.001:125860171'
    - id: '2012_2013'
      granule_ur: 'SC:NSIDC-0642.001:125860173'
    - id: '2014_2015'
      granule_ur: 'SC:NSIDC-0642.001:125860177'
    - id: '2015_2016'
      granule_ur: 'SC:NSIDC-0642.001:125860175'
    - id: '2016_2017'
      granule_ur: 'SC:NSIDC-0642.001:125860184'
  metadata:
    title: 'MEaSUREs Annual Greenland Outlet Glacier Terminus Positions from SAR Mosaics, Version 1'
    abstract: 'This data set, part of the NASA Making Earth System Data Records for Use in Research Environments (MEaSUREs) program, provides Greenland outlet glacier terminus positions created from MEaSUREs Synthetic Aperture Radar (SAR) mosaics and Landsat 8 OLI imagery.'
    citation:
      text: 'Joughin, I., T. Moon, J. Joughin, and T. Black. 2015, 2017. MEaSUREs Annual Greenland Outlet Glacier Terminus Positions from SAR Mosaics, Version 1. [Indicate subset used]. Boulder, Colorado USA. NASA National Snow and Ice Data Center Distributed Active Archive Center. doi: https://doi.org/10.5067/DC0MLBOCL3EL. 2020/02/12.'
      url: 'https://doi.org/10.5067/DC0MLBOCL3EL'

- id: hydrologic_subbasins
  access_method: http
  sources:
    - id: only
      urls:
        - 'https://daacdata.apps.nsidc.org/pub/DATASETS/parca/nsidc-0371-hydrologic-sub-basins/Greenland_Hydrologic_Sub_Basins.rar'
  metadata:
    title: 'Hydrologic Sub-basins of Greenland, Version 1'
    abstract: "The Hydrologic Sub-basins of Greenland data set contains Geographic Information System (GIS) polygon shapefiles that include 293 hydrologic sub-basins of the Greenland Ice Sheet, as created by Lewis and Smith (2009). Five km Digital Elevation Models (DEMs) of ice-surface and bedrock topography (Bamber et al. 2001) were used to estimate the hydraulic potentiometric surface for Greenland, which accounts for the effects of ice overburden pressure, such as hydrostatic pressure, surface topography, and underlying bedrock topography (Paterson 1994). Using the 5 km potentiometric grid, a modeled basin network for Greenland's ice sheet was created using the hydrological tools within ESRI ArcGIS (ArcInfo 9.2). Although the GIS initially generated more than 293 basins, basins less than 100 km2 in size, as well as basins located completely outside of the ice sheet extent, were removed from the data set."
    citation:
      text: ' Sarah Lewis 2009. Hydrologic Sub-basins of Greenland, Version 1. Boulder, Colorado USA. NSIDC: National Snow and Ice Data Center. doi: https://doi.org/10.5067/DT9T7DPD7HBI. [2020/03/18].'
      url: 'https://doi.org/10.5067/DT9T7DPD7HBI'


- id: avhrr_biomass_2010
  access_method: cmr
  sources:
    - id: only
      granule_ur: 'Arctic_Vegetation_Maps.aga_circumpolar_avhrr_biomass_2010.tif'
  metadata:
    title: 'Circumpolar Arctic Vegetation, Geobotanical, Physiographic Maps, 1982-2003'
    abstract: 'This data set provides the spatial distributions of vegetation types, geobotanical characteristics, and physiographic features for the circumpolar Arctic tundra biome for the period 1982-2003. Specific attributes include dominant vegetation, bioclimate subzones, floristic subprovinces, landscape types, lake coverage, Arctic treeline, elevation, and substrate chemistry data. Vegetation indices, trends, and biomass estimate products for the circumpolar Arctic through 2010 are also provided.'
    citation:
      text: 'Walker, D.A., and M.K. Raynolds. 2018. Circumpolar Arctic Vegetation, Geobotanical, Physiographic Maps, 1982-2003. ORNL DAAC, Oak Ridge, Tennessee, USA. https://doi.org/10.3334/ORNLDAAC/1323'
      url: 'https://doi.org/10.3334/ORNLDAAC/1323'
