Miscellaneous:
  visible: False
  expanded: True

Miscellaneous/Place names:
  visible: False
  expanded: False

Miscellaneous/Latitude lines:
  visible: False
  expanded: False

Miscellaneous/Longitude lines:
  visible: False
  expanded: False


Atmosphere:
  visible: False
  expanded: False

Atmosphere/RACMO model output:
  visible: False
  expanded: False

Atmosphere/ERA5 Re-analysis:
  visible: False
  expanded: False


Biology:
  visible: True
  expanded: False

Biology/Fish:
  visible: False
  expanded: False

Biology/Birds:
  visible: False
  expanded: False

Biology/Mammals:
  visible: False
  expanded: False

Biology/Vegetation:
  visible: False 
  expanded: True 


Built environment:
  visible: True
  expanded: False


Environmental management:
  visible: False
  expanded: False

Environmental management/Protected zones:
  visible: False
  expanded: False

Environmental management/Exclusive economic zones:
  visible: False
  expanded: False


Frozen ground:
  visible: True
  expanded: True


Future projections:
  visible: False
  expanded: False


Glaciology:
  visible: True
  expanded: True

Glaciology/Glacier terminus positions 2000-2017:
  visible: True
  expanded: False

Glaciology/Ice sheet velocity:
  visible: True
  expanded: False

Glaciology/Ice thickness change:
  visible: True
  expanded: False


Geology & natural resources:
  visible: True
  expanded: True


Geophysics:
  visible: False
  expanded: False


Human activity:
  visible: False
  expanded: False

Human activity/Arctic shipping:
  visible: False
  expanded: False

Human activity/Research stations:
  visible: False
  expanded: False

Human activity/Historic expedition routes and stations:
  visible: False
  expanded: False


Human health:
  visible: False
  expanded: False


Hydrology:
  visible: True
  expanded: True


Oceanography:
  visible: True
  expanded: True


Sea ice:
  visible: True
  expanded: True

Sea ice/Median ice extent:
  visible: False
  expanded: False

Sea ice/NSIDC Concentration (25 km):
  visible: False
  expanded: True

Sea ice/NSIDC Concentration (25 km)/September (min extent):
  visible: False
  expanded: False

Sea ice/NSIDC Concentration (25 km)/Feb|March (max extent):
  visible: False
  expanded: False


Social Science:
  visible: False
  expanded: False


Terrain models:
  visible: True
  expanded: True

Terrain models/BedMachine:
  visible: False
  expanded: False


Satellite imagery:
  visible: False
  expanded: False


Basemaps:
  visible: True
  expanded: True
