Miscellaneous:
  visible: False
  # The first group will be automatically expanded by QGIS, but we don't want
  # that:(
  expanded: False

Miscellaneous/Latitude lines:
  visible: False
  expanded: False

Miscellaneous/Longitude lines:
  visible: False
  expanded: False


Atmosphere:
  visible: False
  expanded: False

Atmosphere/RACMO model output:
  visible: False
  expanded: False


Biology:
  visible: False
  expanded: False

Biology/Fish:
  visible: False
  expanded: False

Biology/Birds:
  visible: False
  expanded: False

Biology/Mammals:
  visible: False
  expanded: False

Biology/Vegetation:
  visible: False
  expanded: False


Built environment:
  visible: True
  expanded: False


Environmental management:
  visible: False
  expanded: False

Environmental management/Protected zones:
  visible: False
  expanded: False

Environmental management/Exclusive economic zones:
  visible: False
  expanded: False


Frozen ground:
  visible: False
  expanded: False


Future projections:
  visible: False
  expanded: False


Glaciology:
  visible: False
  expanded: False

Glaciology/Glacier terminus positions 2000-2017:
  visible: False
  expanded: False

# TODO: Do we need this group? Why would we want >1 layer in this group?
Glaciology/Ice sheet velocity:
  visible: False
  expanded: False

# TODO: Do we need this group? Why would we want >1 layer in this group?
Glaciology/Ice thickness change:
  visible: False
  expanded: False

Glaciology/Surface elevation change:
  visible: False
  expanded: False

Glaciology/Surface elevation change/Observations:
  visible: False
  expanded: False

Glaciology/Surface elevation change/Errors:
  visible: False
  expanded: False


Geology & natural resources:
  visible: False
  expanded: False


Geophysics:
  visible: False
  expanded: False

Geophysics/World Magnetic Model:
  visible: False
  expanded: False

Geophysics/World Magnetic Model/Dip Poles:
  visible: False
  expanded: False

Geophysics/World Magnetic Model/Geomagnetic Coordinates (2020):
  visible: False
  expanded: False

Geophysics/World Magnetic Model/2020:
  visible: False
  expanded: False

Geophysics/World Magnetic Model/2021:
  visible: False
  expanded: False

Geophysics/World Magnetic Model/2022:
  visible: False
  expanded: False

Geophysics/World Magnetic Model/2023:
  visible: False
  expanded: False

Geophysics/World Magnetic Model/2024:
  visible: False
  expanded: False

Geophysics/World Magnetic Model/2025:
  visible: False
  expanded: False

Human activity:
  visible: False
  expanded: False

Human activity/Research stations:
  visible: False
  expanded: False


Hydrology:
  visible: False
  expanded: False


Oceanography:
  visible: False
  expanded: False

Oceanography/IHO-ICO GEBCO Undersea feature names:
  visible: False
  expanded: False

Oceanography/World Ocean Atlas (WOA) 2018:
  visible: False
  expanded: False


Sea ice:
  visible: False
  expanded: False

Sea ice/Median ice extent:
  visible: False
  expanded: False

Sea ice/NSIDC Concentration (25 km):
  visible: False
  expanded: True

Sea ice/NSIDC Concentration (25 km)/September (min extent):
  visible: False
  expanded: False

Sea ice/NSIDC Concentration (25 km)/Feb or March (max extent):
  visible: False
  expanded: False


Terrain models:
  visible: False
  expanded: False

Terrain models/BedMachine:
  visible: False
  expanded: False


Internet-required data:
  visible: False
  expanded: False


Basemaps:
  visible: True
  expanded: False
